### ISSUE TITLE
Dynamic load content to panel

### ISSUE THREAD

**Issue by koolll** [wnielson/sencha-SlideNavigation#16]
Hi, I got a question. Is it possible to dynamic load content inside the navigation panel? for example click member button will show a member detail , click transaction button will show a transaction detail.

 Here the screen shoot
![screen1](https://f.cloud.github.com/assets/3002496/12783/c7d3b5a4-45c2-11e2-955e-37e4fe430437.png)

As you see, my tabpanel contain 3 item which is loyalty , member list and transaction list. Each panel consist of difference navigation panel.Is it possible to dynamic load content inside the navigation panel when I select other tab

Btw i has change the "createNavigationList" to a panel. Please guild me some example.Your help is much appreciated. Thanks

**Comment by wnielson** [comment]
Sure.  You can get the list that belongs to the slidenavigation view and then update the associated store's data accordingly.

In the future, if you have a question please ask it in the [Sencha Touch Forum](http://www.sencha.com/forum/forumdisplay.php?89-Sencha-Touch-2.x-Forums) instead of creating a new issue here.  This is really meant for keeping track of bugs and features, not support requests.

Cheers.
