### ISSUE TITLE
Drag anywhere on container

### ISSUE THREAD

**Issue by donaldruby** [wnielson/sencha-SlideNavigation#20]
I need to be able to drag from anywhere on the container, not just toolbar or button.  What changes would be needed to do that?

**Comment by wnielson** [comment]
This is actually already possible.  If you change `slideSelector` to 'x-container' it will just work.  However, the problem is that it makes horizontal scrolling within the container a bit annoying.  A solution would be to add a delay to the horizontal dragging, essentially making it "sticky".  This would be a nice addition, so I'll look into it.

**Comment by wnielson** [comment]
I've implemented a basic version of this.  You can control the horisontal sensitivity via the `containerSlideDelay` config option.  It isn't perfect yet as it doesn't work when the container is masked, but it is useable.
