### ISSUE TITLE
Using Ext.Viewport.animateActiveItem with a SlideNavigation component does not work.

### ISSUE THREAD

**Issue by ElMassimo** [wnielson/sencha-SlideNavigation#23]
If you attempt to navigate to a SlideNavigation component from other component the SlideNavigation is not shown (visibility: hidden).

If you can't replicate it I could send attach an example.

**Comment by wnielson** [comment]
How about a patch :p

I'll take a look at it.  Thanks for the report.

Sent from my iPhone

On Feb 1, 2013, at 6:12 AM, ElMassimo notifications@github.com wrote:

If you attempt to navigate to a SlideNavigation component from other
component the SlideNavigation is not shown (visibility: hidden).

If you can't replicate it I could send attach an example.

—
Reply to this email directly or view it on
GitHubhttps://github.com/wnielson/sencha-SlideNavigation/issues/23.

**Comment by wnielson** [comment]
Reading this further, I'm not quite sure I understand the issue completely.  An example would be great.

**Comment by ginkouno** [comment]
I'm in same situation.

First, show another view.

Next, do this:

  var navi = this.getSlideNavigationView(); 
  Ext.Viewport.animateActiveItem(navi,  { type: 'slide' });  

But, it does not  work.
SlideNavigationView does not come.

I think, the reason is that exist two same id elements in document.

Ext.Viewport.animateActiveItem search container from id, but first element is not container.
First element is '<style type="text/css" id="navigation_view_id" ....'.

Ext.Vewport.animateActiveItem wants to remove 'visibility' property at '<div class="x-container....", id="navigation_view_id" ...' . It is second element.

So, If set 'shadowStyle: false' or disable createContainerCSS , Ext.Viewport.animateActiveItem can work.

I thank you for reading it through.

**Comment by ElMassimo** [comment]
Excellent! It's working properly now!
Thanks for looking into it!
